// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVC-eT5aYPSICvMpyJy2sgQGK_KXrqHGg',
    appId: '1:130349712683:web:6b977ca66edc70acd1316e',
    messagingSenderId: '130349712683',
    projectId: 'to-do-list-project-93f0f',
    authDomain: 'to-do-list-project-93f0f.firebaseapp.com',
    storageBucket: 'to-do-list-project-93f0f.firebasestorage.app',
    measurementId: 'G-74E8YSR8EE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-fj2M9C3225J6p5M9l_-1a4IKUwOi3t4',
    appId: '1:130349712683:ios:318446f42db51b69d1316e',
    messagingSenderId: '130349712683',
    projectId: 'to-do-list-project-93f0f',
    storageBucket: 'to-do-list-project-93f0f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-fj2M9C3225J6p5M9l_-1a4IKUwOi3t4',
    appId: '1:130349712683:ios:318446f42db51b69d1316e',
    messagingSenderId: '130349712683',
    projectId: 'to-do-list-project-93f0f',
    storageBucket: 'to-do-list-project-93f0f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVC-eT5aYPSICvMpyJy2sgQGK_KXrqHGg',
    appId: '1:130349712683:web:29e9d38a211fa301d1316e',
    messagingSenderId: '130349712683',
    projectId: 'to-do-list-project-93f0f',
    authDomain: 'to-do-list-project-93f0f.firebaseapp.com',
    storageBucket: 'to-do-list-project-93f0f.firebasestorage.app',
    measurementId: 'G-SK4EWBK4Y1',
  );

}